# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html


# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import os
import sys

from sphinx_typlog_theme import add_badge_roles

sys.path.insert(0, os.path.abspath('../../pybox'))


# -- Project information -----------------------------------------------------

project = 'PyBox'
copyright = '2020, Gregor Minnemann'
author = 'Gregor Minnemann'
version = '0.0.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo'
]

# The master toctree document.
master_doc = 'index'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'de'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_typlog_theme'
html_theme_options = {
    'color': '#1C8074',
    'logo': 'computer.png',
    'logo_name': 'PyBox',
    'description': 'A simple Text Adventure Framework written in Python.',
    'github_user': 'Abl3t0nnile',
    'github_repo': 'pybox',
    'meta_html': '<meta name="generator" content="sphinx">'
}
#html_theme_path = [".."]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".

html_static_path = ['_static']

html_sidebars = {
    '**': [
        'logo.html',
        'github.html',
        'globaltoc.html',
        'searchbox.html',
    ]
}

# -- Extension configuration -------------------------------------------------

# pygments_style = 'flasky'

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

def setup(app):
    add_badge_roles(app)